import type {
  BoardComment,
  BoardPost,
  Concept,
  Folder,
  LeagueEntry,
  Lecture,
  RecordingFolder,
  ReviewItem,
  UserSummary,
} from './types'

// 홈 화면을 채우기 위한 목 데이터. 실제 DB가 붙으면 server/ 에서 교체한다.

export const me: UserSummary = {
  name: '하늘',
  xpTotal: 1840,
  xpThisWeek: 260,
  streakDays: 6,
  leagueRank: 4,
  leagueSize: 30,
  // 데모가 언제 열려도 "어제까지 6일 연속, 오늘은 아직"으로 시작하게 어제 날짜로 둔다.
  lastStudyDate: localDate(-1),
  todaySolved: 0,
  dailyGoal: 10,
}

// 로컬 기준 날짜 문자열. offset: 오늘에서 며칠 더하거나 뺄지
export function localDate(offset = 0) {
  const d = new Date()
  d.setDate(d.getDate() + offset)
  const p = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${p(d.getMonth() + 1)}-${p(d.getDate())}`
}

export const lectures: Lecture[] = [
  {
    id: 'lec_1',
    title: '9/30 자료구조',
    course: '자료구조',
    recordedAt: '2026-09-30',
    durationMin: 74,
    status: 'ready',
    cardCount: 12,
    quizCount: 10,
  },
  {
    id: 'lec_2',
    title: '9/29 운영체제',
    course: '운영체제',
    recordedAt: '2026-09-29',
    durationMin: 68,
    status: 'ready',
    cardCount: 9,
    quizCount: 8,
  },
  {
    id: 'lec_3',
    title: '10/1 데이터베이스',
    course: '데이터베이스',
    recordedAt: '2026-10-01',
    durationMin: 52,
    status: 'processing',
    cardCount: 0,
    quizCount: 0,
  },
  {
    id: 'lec_0',
    title: '9/16 자료구조',
    course: '자료구조',
    recordedAt: '2026-09-16',
    durationMin: 71,
    status: 'ready',
    cardCount: 8,
    quizCount: 10,
  },
  // 지난 녹음들(개념 없음). 녹음본 목록이 10개를 넘어 2페이지가 생기는지 보는 용도
  {
    id: 'lec_m1',
    title: '9/15 운영체제',
    course: '운영체제',
    recordedAt: '2026-09-15',
    durationMin: 66,
    status: 'ready',
    cardCount: 0,
    quizCount: 0,
  },
  {
    id: 'lec_m2',
    title: '9/14 데이터베이스',
    course: '데이터베이스',
    recordedAt: '2026-09-14',
    durationMin: 50,
    status: 'ready',
    cardCount: 0,
    quizCount: 0,
  },
  {
    id: 'lec_m3',
    title: '9/9 자료구조',
    course: '자료구조',
    recordedAt: '2026-09-09',
    durationMin: 73,
    status: 'ready',
    cardCount: 0,
    quizCount: 0,
  },
  {
    id: 'lec_m4',
    title: '9/8 운영체제',
    course: '운영체제',
    recordedAt: '2026-09-08',
    durationMin: 70,
    status: 'ready',
    cardCount: 0,
    quizCount: 0,
  },
  {
    id: 'lec_m5',
    title: '9/7 데이터베이스',
    course: '데이터베이스',
    recordedAt: '2026-09-07',
    durationMin: 48,
    status: 'ready',
    cardCount: 0,
    quizCount: 0,
  },
  {
    id: 'lec_m6',
    title: '9/2 자료구조',
    course: '자료구조',
    recordedAt: '2026-09-02',
    durationMin: 75,
    status: 'ready',
    cardCount: 0,
    quizCount: 0,
  },
  {
    id: 'lec_m7',
    title: '9/1 운영체제',
    course: '운영체제',
    recordedAt: '2026-09-01',
    durationMin: 64,
    status: 'ready',
    cardCount: 0,
    quizCount: 0,
  },
  {
    id: 'lec_m8',
    title: '8/31 데이터베이스',
    course: '데이터베이스',
    recordedAt: '2026-08-31',
    durationMin: 55,
    status: 'ready',
    cardCount: 0,
    quizCount: 0,
  },
]

export const concepts: Concept[] = [
  {
    id: 'con_1',
    term: '이진 탐색 트리',
    summary: '왼쪽 서브트리 < 노드 < 오른쪽 서브트리를 항상 지키는 트리. 균형이 맞으면 탐색이 O(log n).',
    lectureId: 'lec_1',
    lectureTitle: '9/30 자료구조',
    course: '자료구조',
    mastery: 'new',
  },
  {
    id: 'con_2',
    term: '중위 순회',
    summary: '왼쪽 → 노드 → 오른쪽 순서로 방문. BST에서 하면 오름차순으로 나온다.',
    lectureId: 'lec_1',
    lectureTitle: '9/30 자료구조',
    course: '자료구조',
    mastery: 'learning',
  },
  {
    id: 'con_3',
    term: '노드 삭제와 후계자',
    summary: '자식이 둘인 노드를 지울 땐 오른쪽 서브트리의 최솟값(중위 후계자)으로 바꿔 넣는다.',
    lectureId: 'lec_1',
    lectureTitle: '9/30 자료구조',
    course: '자료구조',
    mastery: 'new',
  },
  {
    id: 'con_4',
    term: '프로세스와 스레드',
    summary: '프로세스는 독립된 메모리 공간을 갖고, 스레드는 같은 프로세스 안에서 코드·데이터·힙을 공유한다.',
    lectureId: 'lec_2',
    lectureTitle: '9/29 운영체제',
    course: '운영체제',
    mastery: 'learning',
  },
  {
    id: 'con_5',
    term: '컨텍스트 스위칭',
    summary: 'CPU가 실행 중인 작업을 바꿀 때 레지스터 등 상태를 PCB에 저장하고 다음 작업 상태를 불러오는 과정.',
    lectureId: 'lec_2',
    lectureTitle: '9/29 운영체제',
    course: '운영체제',
    mastery: 'new',
  },
  {
    id: 'con_6',
    term: '연결 리스트',
    summary: '각 노드가 다음 노드의 주소를 가리키는 구조. 중간 삽입·삭제는 O(1), 임의 접근은 O(n).',
    lectureId: 'lec_0',
    lectureTitle: '9/16 자료구조',
    course: '자료구조',
    mastery: 'mastered',
  },
]

export const todayReviews: ReviewItem[] = [
  {
    id: 'rev_1',
    lectureId: 'lec_2',
    lectureTitle: '9/29 운영체제',
    course: '운영체제',
    reason: 'wrong',
    questionCount: 3,
  },
  {
    id: 'rev_2',
    lectureId: 'lec_0',
    lectureTitle: '9/16 자료구조',
    course: '자료구조',
    reason: 'interval',
    questionCount: 5,
  },
]

export const league: LeagueEntry[] = [
  { rank: 1, name: '민준', xpThisWeek: 410 },
  { rank: 2, name: '서연', xpThisWeek: 380 },
  { rank: 3, name: '지호', xpThisWeek: 295 },
  { rank: 4, name: '하늘', xpThisWeek: 260, isMe: true },
  { rank: 5, name: '유진', xpThisWeek: 240 },
]

// 게시판 글(목). 시각은 앱을 연 때 기준으로 몇 분 전으로 잡아 "방금 · 9분 전"처럼 보이게 한다.
export const ME_ID = 'me'

function minutesAgo(m: number) {
  return new Date(Date.now() - m * 60_000).toISOString()
}

export const posts: BoardPost[] = [
  // 내가 쓴 글: 수정·삭제 버튼과 '글쓴이' 표시, 내 댓글에 달린 대댓글에 답해 보는 용도
  {
    id: 'post_me1',
    board: 'question',
    title: '자료구조 과제 2번 어디까지 써야 하나요?',
    body: '구현만 하면 되는 건지, 시간복잡도 분석까지 써야 하는 건지 헷갈려요.',
    tags: ['자료구조', '과제'],
    anonymous: true,
    author: '익명',
    authorId: ME_ID,
    likes: 2,
    liked: false,
    commentCount: 2,
    createdAt: minutesAgo(15),
  },
  // 댓글이 하나도 없는 글: 직접 댓글·대댓글을 달아 보는 용도
  {
    id: 'post_f0',
    board: 'free',
    title: '오늘 학식 뭐 나왔어요?',
    body: '공강이라 늦게 가는데 먹을 만한지 궁금해요',
    tags: ['학식', '잡담'],
    anonymous: true,
    author: '익명',
    authorId: 'u_12',
    likes: 1,
    liked: false,
    commentCount: 0,
    createdAt: minutesAgo(1),
  },
  {
    id: 'post_f1',
    board: 'free',
    title: '도서관 4층 콘센트 자리 꿀팁',
    body: '창가 쪽 끝자리 책상 밑에 콘센트 두 개 있어요.\n시험 기간엔 8시 전에 가야 남아 있음',
    tags: ['도서관', '꿀팁'],
    anonymous: true,
    author: '익명',
    authorId: 'u_2',
    likes: 12,
    liked: false,
    commentCount: 2,
    createdAt: minutesAgo(3),
  },
  {
    id: 'post_q1',
    board: 'question',
    title: '힙 정렬이 왜 불안정 정렬인가요?',
    body: '교수님이 힙 정렬은 stable하지 않다고 하셨는데 예시가 잘 안 떠올라요. 같은 값이 있을 때 순서가 바뀌는 예 있을까요?',
    tags: ['자료구조', '정렬'],
    anonymous: true,
    author: '익명',
    authorId: 'u_3',
    likes: 4,
    liked: false,
    commentCount: 2,
    createdAt: minutesAgo(9),
  },
  {
    id: 'post_1',
    board: 'study',
    title: '자료구조 중간고사 대비 스터디',
    body: '주 2회 저녁에 모여서 기출 풀어요. 트리·그래프 위주로 할 예정입니다.',
    tags: ['자료구조', '중간고사'],
    anonymous: false,
    author: '감자칩',
    authorId: 'u_4',
    likes: 7,
    liked: false,
    commentCount: 1,
    createdAt: minutesAgo(12),
    study: { course: '자료구조', minXp: 1000, capacity: 4, joined: 2 },
  },
  {
    id: 'post_f2',
    board: 'free',
    title: '녹음 요약 써봤는데 생각보다 괜찮네요',
    body: '74분짜리 강의가 개념 3개로 정리됨. 플래시카드로 넘기니까 버스에서 보기 좋아요',
    tags: ['후기', '자료구조'],
    anonymous: false,
    author: '감자칩',
    authorId: 'u_4',
    likes: 21,
    liked: true,
    commentCount: 0,
    createdAt: minutesAgo(19),
  },
  {
    id: 'post_q2',
    board: 'question',
    title: '3NF랑 BCNF 차이 쉽게 설명해 주실 분',
    body: '정의는 외웠는데 문제에서 어느 쪽인지 판단이 안 돼요ㅠ',
    tags: ['데이터베이스', '시험'],
    anonymous: true,
    author: '익명',
    authorId: 'u_5',
    likes: 9,
    liked: false,
    commentCount: 4,
    createdAt: minutesAgo(47),
  },
  {
    id: 'post_2',
    board: 'study',
    title: '운영체제 과제 같이 풀어요',
    body: '스케줄링 시뮬레이터 과제요. 코드 리뷰 서로 해 줄 분.',
    tags: ['운영체제', '과제'],
    anonymous: true,
    author: '익명',
    authorId: 'u_6',
    likes: 3,
    liked: false,
    commentCount: 0,
    createdAt: minutesAgo(95),
    study: { course: '운영체제', minXp: 500, capacity: 3, joined: 3 },
  },
  {
    id: 'post_f3',
    board: 'free',
    title: '중간고사 끝나면 뭐 하세요',
    body: '저는 일단 이틀 내리 잘 거예요',
    tags: ['잡담'],
    anonymous: true,
    author: '익명',
    authorId: 'u_7',
    likes: 5,
    liked: false,
    commentCount: 0,
    createdAt: minutesAgo(180),
  },
  {
    id: 'post_q3',
    board: 'question',
    title: '컨텍스트 스위칭 비용에 TLB 비우는 것도 포함되나요?',
    body: '스레드끼리 바뀔 때랑 프로세스끼리 바뀔 때 차이가 궁금합니다.',
    tags: ['운영체제'],
    anonymous: false,
    author: '새벽코딩',
    authorId: 'u_8',
    likes: 2,
    liked: false,
    commentCount: 0,
    createdAt: minutesAgo(320),
  },
  {
    id: 'post_3',
    board: 'study',
    title: '데이터베이스 기말 벼락치기 방',
    body: '기말 2주 전부터 매일 1시간씩 정규화·SQL 문제 풀이.',
    tags: ['데이터베이스', '기말'],
    anonymous: false,
    author: '새벽코딩',
    authorId: 'u_8',
    likes: 6,
    liked: false,
    commentCount: 0,
    createdAt: minutesAgo(1500),
    study: { course: '데이터베이스', minXp: 2000, capacity: 5, joined: 1 },
  },
]

export const comments: BoardComment[] = [
  { id: 'cmt_1', postId: 'post_f1', body: '오 감사합니다', author: '익명1', authorId: 'u_9', isWriter: false, createdAt: minutesAgo(2) },
  { id: 'cmt_2', postId: 'post_f1', body: '8시 전이면 거의 문 열자마자네요ㅋㅋ', author: '익명2', authorId: 'u_10', isWriter: false, createdAt: minutesAgo(1) },
  {
    id: 'cmt_3',
    postId: 'post_q1',
    body: '[5a, 5b, 3] 같은 배열로 힙 만들고 빼 보면 5a와 5b 순서가 뒤집혀요. 루트를 맨 뒤와 바꾸는 과정 때문!',
    author: '익명1',
    authorId: 'u_9',
    isWriter: false,
    createdAt: minutesAgo(6),
  },
  { id: 'cmt_4', postId: 'post_q1', body: '아하 이해됐어요 감사합니다', author: '익명(글쓴이)', authorId: 'u_3', isWriter: true, createdAt: minutesAgo(4) },
  { id: 'cmt_5', postId: 'post_1', body: '혹시 시간대는 몇 시쯤인가요?', author: '익명1', authorId: 'u_2', isWriter: false, createdAt: minutesAgo(10) },
  // 내 글(post_me1)에 내가 단 댓글과, 거기에 다른 사람이 단 대댓글
  {
    id: 'cmt_me1',
    postId: 'post_me1',
    body: '참고로 과제 공지는 이캠퍼스 3주차 자료실에 있어요.',
    author: '익명(글쓴이)',
    authorId: ME_ID,
    isWriter: true,
    createdAt: minutesAgo(13),
  },
  {
    id: 'cmt_me2',
    postId: 'post_me1',
    parentId: 'cmt_me1',
    body: '공지 봤는데 2번은 시간복잡도까지 쓰라고 되어 있었어요! 빅오만 적으면 된대요.',
    author: '익명1',
    authorId: 'u_15',
    isWriter: false,
    createdAt: minutesAgo(8),
  },
  // 대댓글 흐름 예시: 익명1 → 익명2 → 익명1 → 익명2 (모두 원댓글 cmt_6 아래)
  {
    id: 'cmt_6',
    postId: 'post_q2',
    body: 'BCNF는 "모든 결정자가 후보키"여야 하고, 3NF는 결정자가 후보키가 아니어도 결정되는 쪽이 주식별자의 일부면 봐줘요. 그래서 BCNF가 더 빡빡해요.',
    author: '익명1',
    authorId: 'u_13',
    isWriter: false,
    createdAt: minutesAgo(40),
  },
  {
    id: 'cmt_7',
    postId: 'post_q2',
    parentId: 'cmt_6',
    body: '그럼 3NF인데 BCNF는 아닌 예시가 있을까요?',
    author: '익명2',
    authorId: 'u_14',
    isWriter: false,
    createdAt: minutesAgo(35),
  },
  {
    id: 'cmt_8',
    postId: 'post_q2',
    parentId: 'cmt_6',
    body: '수강(학생, 과목, 교수)에서 교수 → 과목인데 교수가 후보키가 아니면 3NF지만 BCNF는 아니에요. 교수 테이블을 따로 빼면 BCNF 돼요.',
    author: '익명1',
    authorId: 'u_13',
    isWriter: false,
    createdAt: minutesAgo(30),
  },
  {
    id: 'cmt_9',
    postId: 'post_q2',
    parentId: 'cmt_6',
    body: '아 결정자를 먼저 찾으면 되는 거군요. 감사합니다!',
    author: '익명2',
    authorId: 'u_14',
    isWriter: false,
    createdAt: minutesAgo(26),
  },
]

// 스터디 모집 글의 연락처. 조건을 채워 참여한 사람에게만 보여준다.
export const studyContacts: Record<string, string> = {
  post_1: 'https://open.kakao.com/o/sample1',
  post_2: 'https://open.kakao.com/o/sample2',
  post_3: 'https://open.kakao.com/o/sample3',
}

// 사용자가 만든 녹음 폴더(목).
export const recordingFolders: RecordingFolder[] = [
  { id: 'rfd_1', name: '중간고사 녹음', lectureIds: ['lec_1', 'lec_2'], createdAt: '2026-09-30' },
]

// 녹음에 다는 내 태그(목). 과목과 별개로 사용자가 만든다.
export const recordingTagList: string[] = ['시험범위', '다시듣기']
export const lectureTags: Record<string, string[]> = {
  lec_1: ['시험범위'],
  lec_2: ['시험범위', '다시듣기'],
}

// 사용자가 만든 개념 폴더(목). 새로 녹음해서 생긴 개념은 어느 폴더에도 안 들어간 상태로 시작한다.
export const folders: Folder[] = [
  {
    id: 'fld_1',
    name: '중간고사 범위',
    conceptIds: ['con_1', 'con_2', 'con_3', 'con_4', 'con_5'],
    createdAt: '2026-09-28',
  },
  {
    id: 'fld_2',
    name: '자주 틀리는 것',
    conceptIds: ['con_4', 'con_2'],
    createdAt: '2026-09-30',
  },
]
